/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.ImageIcon;

/**
 *
 * @author sebas
 */
public class Presentacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Presentacion.class.getName());

    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        setTitle("edEXT");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ModUsuario = new javax.swing.JMenu();
<<<<<<< HEAD
        jMenuItem1 = new javax.swing.JMenuItem();
        mConsultarUsuario = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuAltaCurso = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        itemMenuInsEdi = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        CrearProgFormacion = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
=======
        AltaUsuarioMenuItem = new javax.swing.JMenuItem();
        ConsultaUsuarioMenuItem = new javax.swing.JMenuItem();
        ModificarUsuarioMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        IngresarCursoMenuItem = new javax.swing.JMenuItem();
        ConsultaCursoMenuItem = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        IngresarEdicionMenuItem = new javax.swing.JMenuItem();
        ConsultaEdicionMenuItem = new javax.swing.JMenuItem();
        InscripcionEdicionMenuItem = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        CrearProgramaMenuItem = new javax.swing.JMenuItem();
        AgregarCursoProgramaMenuItem = new javax.swing.JMenuItem();
        ConsultaProgramaMenuItem = new javax.swing.JMenuItem();
        InscripcionProgramaMenuItem = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        AltaInstitutoMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        AltaCategoriaMenuItem = new javax.swing.JMenuItem();
>>>>>>> v2.0.1

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        ModUsuario.setText("Usuarios");

<<<<<<< HEAD
        jMenuItem1.setText("Alta de Usuario");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        ModUsuario.add(jMenuItem1);

        mConsultarUsuario.setText("Consultar Usuario");
        mConsultarUsuario.addActionListener(this::mConsultarUsuarioActionPerformed);
        ModUsuario.add(mConsultarUsuario);

        jMenuItem10.setText("Modificar");
        jMenuItem10.addActionListener(this::jMenuItem10ActionPerformed);
        ModUsuario.add(jMenuItem10);
=======
        AltaUsuarioMenuItem.setText("Alta de Usuario");
        AltaUsuarioMenuItem.addActionListener(this::AltaUsuarioMenuItemActionPerformed);
        ModUsuario.add(AltaUsuarioMenuItem);

        ConsultaUsuarioMenuItem.setText("Consultar Usuario");
        ConsultaUsuarioMenuItem.addActionListener(this::ConsultaUsuarioMenuItemActionPerformed);
        ModUsuario.add(ConsultaUsuarioMenuItem);

        ModificarUsuarioMenuItem.setText("Modificar Usuario");
        ModificarUsuarioMenuItem.addActionListener(this::ModificarUsuarioMenuItemActionPerformed);
        ModUsuario.add(ModificarUsuarioMenuItem);
>>>>>>> v2.0.1

        jMenuBar1.add(ModUsuario);

        jMenu2.setText("Cursos");

<<<<<<< HEAD
        jMenuAltaCurso.setText("Ingresar");
        jMenuAltaCurso.addActionListener(this::jMenuAltaCursoActionPerformed);
        jMenu2.add(jMenuAltaCurso);

        jMenuItem2.setText("Consultar");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu2.add(jMenuItem2);

        jMenu10.setText("Edicion Curso");

        jMenuItem3.setText("Ingresar");
        jMenuItem3.addActionListener(this::jMenuItem3ActionPerformed);
        jMenu10.add(jMenuItem3);

        jMenuItem11.setText("Consulta");
        jMenuItem11.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu10.add(jMenuItem11);

        itemMenuInsEdi.setText("Inscripcion");
        itemMenuInsEdi.addActionListener(this::itemMenuInsEdiActionPerformed);
        jMenu10.add(itemMenuInsEdi);
=======
        IngresarCursoMenuItem.setText("Ingresar");
        IngresarCursoMenuItem.addActionListener(this::IngresarCursoMenuItemActionPerformed);
        jMenu2.add(IngresarCursoMenuItem);

        ConsultaCursoMenuItem.setText("Consultar");
        ConsultaCursoMenuItem.addActionListener(this::ConsultaCursoMenuItemActionPerformed);
        jMenu2.add(ConsultaCursoMenuItem);

        jMenu10.setText("Edicion Curso");

        IngresarEdicionMenuItem.setText("Ingresar");
        IngresarEdicionMenuItem.addActionListener(this::IngresarEdicionMenuItemActionPerformed);
        jMenu10.add(IngresarEdicionMenuItem);

        ConsultaEdicionMenuItem.setText("Consulta");
        ConsultaEdicionMenuItem.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu10.add(ConsultaEdicionMenuItem);

        InscripcionEdicionMenuItem.setText("Inscripcion");
        InscripcionEdicionMenuItem.addActionListener(this::InscripcionEdicionMenuItemActionPerformed);
        jMenu10.add(InscripcionEdicionMenuItem);
>>>>>>> v2.0.1

        jMenu2.add(jMenu10);

        jMenuBar1.add(jMenu2);

        jMenu11.setText("Prog Formacion");

<<<<<<< HEAD
        CrearProgFormacion.setText("Crear");
        CrearProgFormacion.addActionListener(this::CrearProgFormacionActionPerformed);
        jMenu11.add(CrearProgFormacion);

        jMenuItem5.setText("Agregar Curso");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu11.add(jMenuItem5);

        jMenuItem6.setText("Consultar");
        jMenuItem6.addActionListener(this::jMenuItem6ActionPerformed);
        jMenu11.add(jMenuItem6);

        jMenuItem8.setText("Inscripcion");
        jMenuItem8.addActionListener(this::jMenuItem8ActionPerformed);
        jMenu11.add(jMenuItem8);
=======
        CrearProgramaMenuItem.setText("Crear");
        CrearProgramaMenuItem.addActionListener(this::CrearProgramaMenuItemActionPerformed);
        jMenu11.add(CrearProgramaMenuItem);

        AgregarCursoProgramaMenuItem.setText("Agregar Curso");
        AgregarCursoProgramaMenuItem.addActionListener(this::AgregarCursoProgramaMenuItemActionPerformed);
        jMenu11.add(AgregarCursoProgramaMenuItem);

        ConsultaProgramaMenuItem.setText("Consultar");
        ConsultaProgramaMenuItem.addActionListener(this::ConsultaProgramaMenuItemActionPerformed);
        jMenu11.add(ConsultaProgramaMenuItem);

        InscripcionProgramaMenuItem.setText("Inscripcion");
        InscripcionProgramaMenuItem.addActionListener(this::InscripcionProgramaMenuItemActionPerformed);
        jMenu11.add(InscripcionProgramaMenuItem);
>>>>>>> v2.0.1

        jMenuBar1.add(jMenu11);

        jMenu12.setText("Instituto");

<<<<<<< HEAD
        jMenuItem4.setText("Alta Instituto");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu12.add(jMenuItem4);
=======
        AltaInstitutoMenuItem.setText("Alta Instituto");
        AltaInstitutoMenuItem.addActionListener(this::AltaInstitutoMenuItemActionPerformed);
        jMenu12.add(AltaInstitutoMenuItem);
>>>>>>> v2.0.1

        jMenuBar1.add(jMenu12);

        jMenu1.setText("Categoria");

<<<<<<< HEAD
        jMenuItem7.setText("Alta Categoria");
        jMenuItem7.addActionListener(this::jMenuItem7ActionPerformed1);
        jMenu1.add(jMenuItem7);
=======
        AltaCategoriaMenuItem.setText("Alta Categoria");
        AltaCategoriaMenuItem.addActionListener(this::AltaCategoriaMenuItemActionPerformed1);
        jMenu1.add(AltaCategoriaMenuItem);
>>>>>>> v2.0.1

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
=======
    private void AltaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaUsuarioMenuItemActionPerformed
>>>>>>> v2.0.1
        // 1. Crear la instancia de la ventana interna
        AltaUsuario vAlta = new AltaUsuario();

        // 2. Asignas el tamaño exacto que tenga
        vAlta.setSize(432, 432); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vAlta);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAlta.getSize();
        vAlta.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vAlta.setVisible(true);
        vAlta.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem1ActionPerformed


    private void CrearProgFormacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProgFormacionActionPerformed
                                              
    // 1. Crear una instancia de la ventana interna Programa_Formacion
    Crear_programa_formacion vCrearpf = new Crear_programa_formacion();
    
=======
    }//GEN-LAST:event_AltaUsuarioMenuItemActionPerformed


    private void CrearProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProgramaMenuItemActionPerformed
                                              
    // 1. Crear una instancia de la ventana interna Programa_Formacion
    Crear_programa_formacion vCrearpf = new Crear_programa_formacion();
    vCrearpf.setSize(400,367);
>>>>>>> v2.0.1
    // 2. Agregarla al contenedor principal JDesktopPane
    jDesktopPane1.add(vCrearpf);
    
    // 3. Centrar la ventana dentro del escritorio
    java.awt.Dimension desktopSize = jDesktopPane1.getSize();
    java.awt.Dimension frameSize = vCrearpf.getSize();
    vCrearpf.setLocation((desktopSize.width - frameSize.width) / 2, 
                         (desktopSize.height - frameSize.height) / 2);
    
    // 4. Hacerla visible y traerla al frente
    vCrearpf.setVisible(true);
    vCrearpf.toFront();                                             

<<<<<<< HEAD
    }//GEN-LAST:event_CrearProgFormacionActionPerformed

    private void jMenuAltaCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAltaCursoActionPerformed
=======
    }//GEN-LAST:event_CrearProgramaMenuItemActionPerformed

    private void IngresarCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCursoMenuItemActionPerformed
>>>>>>> v2.0.1
        // 1. Crear la instancia de la ventana interna
        AltaCurso vAlta = new AltaCurso();

        // 2. Asignas el tamaño exacto que tenga
        vAlta.setSize(435, 602); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vAlta);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAlta.getSize();
        vAlta.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vAlta.setVisible(true);
        vAlta.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuAltaCursoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ConsultaCurso vConsultaCurso = new ConsultaCurso();
    
=======
    }//GEN-LAST:event_IngresarCursoMenuItemActionPerformed

    private void ConsultaCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCursoMenuItemActionPerformed
        ConsultaCurso vConsultaCurso = new ConsultaCurso();
        vConsultaCurso.setSize(355,469);
>>>>>>> v2.0.1
        // 2. Agregarla al contenedor principal JDesktopPane
        // (Asegúrate de que 'jDesktopPane1' sea el nombre de variable de tu JDesktopPane)
        jDesktopPane1.add(vConsultaCurso);
    
        // 3. Centrar la ventana dentro del escritorio
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vConsultaCurso.getSize();
        vConsultaCurso.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
    
        // 4. Hacerla visible y traerla al frente
        
        vConsultaCurso.setVisible(true);
        vConsultaCurso.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem2ActionPerformed


    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        AltaEdicionCurso vAltaEdicionCurso = new AltaEdicionCurso();
    
=======
    }//GEN-LAST:event_ConsultaCursoMenuItemActionPerformed


    private void IngresarEdicionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarEdicionMenuItemActionPerformed
        AltaEdicionCurso vAltaEdicionCurso = new AltaEdicionCurso();
        vAltaEdicionCurso.setSize(355,469);
>>>>>>> v2.0.1
        // 2. Agregarla al contenedor principal JDesktopPane
        // (Asegúrate de que 'jDesktopPane1' sea el nombre de variable de tu JDesktopPane)
        jDesktopPane1.add(vAltaEdicionCurso);
    
        // 3. Centrar la ventana dentro del escritorio
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAltaEdicionCurso.getSize();
        vAltaEdicionCurso.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
    
        // 4. Hacerla visible y traerla al frente
        
        vAltaEdicionCurso.setVisible(true);
        vAltaEdicionCurso.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void mConsultarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mConsultarUsuarioActionPerformed
       ConsultaUsuario vConsultaUsuario = new ConsultaUsuario();
=======
    }//GEN-LAST:event_IngresarEdicionMenuItemActionPerformed

    private void ConsultaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioMenuItemActionPerformed
       ConsultaUsuario vConsultaUsuario = new ConsultaUsuario();
       vConsultaUsuario.setSize(582,383);
>>>>>>> v2.0.1
        jDesktopPane1.add(vConsultaUsuario);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vConsultaUsuario.getSize();
        vConsultaUsuario.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vConsultaUsuario.setVisible(true);
        vConsultaUsuario.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_mConsultarUsuarioActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
      AltaInstituto vAltaInstituto = new AltaInstituto();
=======
    }//GEN-LAST:event_ConsultaUsuarioMenuItemActionPerformed

    private void AltaInstitutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaInstitutoMenuItemActionPerformed
      AltaInstituto vAltaInstituto = new AltaInstituto();
      vAltaInstituto.setSize(385,172);
>>>>>>> v2.0.1
       jDesktopPane1.add(vAltaInstituto);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAltaInstituto.getSize();
        vAltaInstituto.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vAltaInstituto.setVisible(true);
        vAltaInstituto.toFront();
      
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
      
        AgregarCursoProgramaForm vAgCurProgForm = new AgregarCursoProgramaForm();
=======
    }//GEN-LAST:event_AltaInstitutoMenuItemActionPerformed

    private void AgregarCursoProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCursoProgramaMenuItemActionPerformed
      
        AgregarCursoProgramaForm vAgCurProgForm = new AgregarCursoProgramaForm();
        vAgCurProgForm.setSize(344,503);
>>>>>>> v2.0.1
        jDesktopPane1.add(vAgCurProgForm);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAgCurProgForm.getSize();
        vAgCurProgForm.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vAgCurProgForm.setVisible(true);
        vAgCurProgForm.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
  interfaces.ConsultaProgramaFormacion vConProgForm = new interfaces.ConsultaProgramaFormacion();
   jDesktopPane1.add(vConProgForm);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
=======
    }//GEN-LAST:event_AgregarCursoProgramaMenuItemActionPerformed

    private void ConsultaProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaProgramaMenuItemActionPerformed
        ConsultaProgramaFormacion vConProgForm = new interfaces.ConsultaProgramaFormacion();
        vConProgForm.setSize(357,310);
        jDesktopPane1.add(vConProgForm);
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
>>>>>>> v2.0.1
        java.awt.Dimension frameSize = vConProgForm.getSize();
        vConProgForm.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vConProgForm.setVisible(true);
        vConProgForm.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem6ActionPerformed
=======
    }//GEN-LAST:event_ConsultaProgramaMenuItemActionPerformed
>>>>>>> v2.0.1


    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ConsultaEdicionCurso vConsultaEdicion = new ConsultaEdicionCurso();
<<<<<<< HEAD
=======
        vConsultaEdicion.setSize(406,368);
>>>>>>> v2.0.1
        jDesktopPane1.add(vConsultaEdicion);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vConsultaEdicion.getSize();
        vConsultaEdicion.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vConsultaEdicion.setVisible(true);
        vConsultaEdicion.toFront();
    }//GEN-LAST:event_jMenuItem7ActionPerformed


<<<<<<< HEAD
    private void itemMenuInsEdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuInsEdiActionPerformed
        InscripcionEdicionCurso vInscripcionEdicion = new InscripcionEdicionCurso();
=======
    private void InscripcionEdicionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionEdicionMenuItemActionPerformed
        InscripcionEdicionCurso vInscripcionEdicion = new InscripcionEdicionCurso();
        vInscripcionEdicion.setSize(400,300);
>>>>>>> v2.0.1
        jDesktopPane1.add(vInscripcionEdicion);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vInscripcionEdicion.getSize();
        vInscripcionEdicion.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vInscripcionEdicion.setVisible(true);
        vInscripcionEdicion.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_itemMenuInsEdiActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ModificarDatosdeUsuario vModificar = new ModificarDatosdeUsuario();
    
        
        jDesktopPane1.add(vModificar);
    
        // 3. Centrar la ventana dentro del escritorio
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vModificar.getSize();
        vModificar.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
    
        // 4. Hacerla visible y traerla al frente
        
        vModificar.setVisible(true);
        vModificar.toFront();// TODO add your handling code here:
    }                                          


    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        InscripcionProgramaDeFormacion vInscripcionPrograma = new InscripcionProgramaDeFormacion();
=======
    }//GEN-LAST:event_InscripcionEdicionMenuItemActionPerformed

    private void InscripcionProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionProgramaMenuItemActionPerformed
        InscripcionProgramaDeFormacion vInscripcionPrograma = new InscripcionProgramaDeFormacion();
        vInscripcionPrograma.setSize(412,500);
>>>>>>> v2.0.1
        jDesktopPane1.add(vInscripcionPrograma);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vInscripcionPrograma.getSize();
        vInscripcionPrograma.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vInscripcionPrograma.setVisible(true);
        vInscripcionPrograma.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed1
=======
    }//GEN-LAST:event_InscripcionProgramaMenuItemActionPerformed

    private void AltaCategoriaMenuItemActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaCategoriaMenuItemActionPerformed1
>>>>>>> v2.0.1
        // 1. Crear la instancia de la ventana interna
        AltaCategoria vAlta = new AltaCategoria();

        // 2. Asignas el tamaño exacto que tenga
        vAlta.setSize(334, 171); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vAlta);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAlta.getSize();
        vAlta.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vAlta.setVisible(true);
        vAlta.toFront();
<<<<<<< HEAD
    }//GEN-LAST:event_jMenuItem7ActionPerformed1


    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {                                            
           ModificarDatosdeUsuario vModificar = new ModificarDatosdeUsuario();
    
        
        jDesktopPane1.add(vModificar);
    
        // 3. Centrar la ventana dentro del escritorio
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vModificar.getSize();
        vModificar.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
    
        // 4. Hacerla visible y traerla al frente
        
        vModificar.setVisible(true);
        vModificar.toFront();// TODO add your handling code here:
    }                                           
=======
    }//GEN-LAST:event_AltaCategoriaMenuItemActionPerformed1

    private void ModificarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioMenuItemActionPerformed
        // 1. Crear la instancia de la ventana interna
        ModificarDatosdeUsuario vMod = new ModificarDatosdeUsuario();

        // 2. Asignas el tamaño exacto que tenga
        vMod.setSize(490, 602); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vMod);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vMod.getSize();
        vMod.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vMod.setVisible(true);
        vMod.toFront();
    }//GEN-LAST:event_ModificarUsuarioMenuItemActionPerformed
                                        
>>>>>>> v2.0.1



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Presentacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JMenuItem CrearProgFormacion;
    private javax.swing.JMenu ModUsuario;
    private javax.swing.JMenuItem itemMenuInsEdi;
=======
    private javax.swing.JMenuItem AgregarCursoProgramaMenuItem;
    private javax.swing.JMenuItem AltaCategoriaMenuItem;
    private javax.swing.JMenuItem AltaInstitutoMenuItem;
    private javax.swing.JMenuItem AltaUsuarioMenuItem;
    private javax.swing.JMenuItem ConsultaCursoMenuItem;
    private javax.swing.JMenuItem ConsultaEdicionMenuItem;
    private javax.swing.JMenuItem ConsultaProgramaMenuItem;
    private javax.swing.JMenuItem ConsultaUsuarioMenuItem;
    private javax.swing.JMenuItem CrearProgramaMenuItem;
    private javax.swing.JMenuItem IngresarCursoMenuItem;
    private javax.swing.JMenuItem IngresarEdicionMenuItem;
    private javax.swing.JMenuItem InscripcionEdicionMenuItem;
    private javax.swing.JMenuItem InscripcionProgramaMenuItem;
    private javax.swing.JMenu ModUsuario;
    private javax.swing.JMenuItem ModificarUsuarioMenuItem;
>>>>>>> v2.0.1
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
<<<<<<< HEAD
    private javax.swing.JMenuItem jMenuAltaCurso;
=======
>>>>>>> v2.0.1
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
<<<<<<< HEAD
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JMenuItem mConsultarUsuario;
=======
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
>>>>>>> v2.0.1
    // End of variables declaration//GEN-END:variables
}
