/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import javax.swing.ImageIcon;

/**
 *
 * @author sebas
 */
public class Presentacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Presentacion.class.getName());

    /**
     * Creates new form Presentacion
     */
    public Presentacion() {
        setTitle("edEXT");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        ModUsuario = new javax.swing.JMenu();
        AltaUsuarioMenuItem = new javax.swing.JMenuItem();
        ConsultaUsuarioMenuItem = new javax.swing.JMenuItem();
        ModificarUsuarioMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        IngresarCursoMenuItem = new javax.swing.JMenuItem();
        ConsultaCursoMenuItem = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        IngresarEdicionMenuItem = new javax.swing.JMenuItem();
        ConsultaEdicionMenuItem = new javax.swing.JMenuItem();
        InscripcionEdicionMenuItem = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        CrearProgramaMenuItem = new javax.swing.JMenuItem();
        AgregarCursoProgramaMenuItem = new javax.swing.JMenuItem();
        ConsultaProgramaMenuItem = new javax.swing.JMenuItem();
        InscripcionProgramaMenuItem = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        AltaInstitutoMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        AltaCategoriaMenuItem = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 276, Short.MAX_VALUE)
        );

        ModUsuario.setText("Usuarios");

        AltaUsuarioMenuItem.setText("Alta de Usuario");
        AltaUsuarioMenuItem.addActionListener(this::AltaUsuarioMenuItemActionPerformed);
        ModUsuario.add(AltaUsuarioMenuItem);

        ConsultaUsuarioMenuItem.setText("Consultar Usuario");
        ConsultaUsuarioMenuItem.addActionListener(this::ConsultaUsuarioMenuItemActionPerformed);
        ModUsuario.add(ConsultaUsuarioMenuItem);

        ModificarUsuarioMenuItem.setText("Modificar Usuario");
        ModificarUsuarioMenuItem.addActionListener(this::ModificarUsuarioMenuItemActionPerformed);
        ModUsuario.add(ModificarUsuarioMenuItem);

        jMenuBar1.add(ModUsuario);

        jMenu2.setText("Cursos");

        IngresarCursoMenuItem.setText("Ingresar");
        IngresarCursoMenuItem.addActionListener(this::IngresarCursoMenuItemActionPerformed);
        jMenu2.add(IngresarCursoMenuItem);

        ConsultaCursoMenuItem.setText("Consultar");
        ConsultaCursoMenuItem.addActionListener(this::ConsultaCursoMenuItemActionPerformed);
        jMenu2.add(ConsultaCursoMenuItem);

        jMenu10.setText("Edicion Curso");

        IngresarEdicionMenuItem.setText("Ingresar");
        IngresarEdicionMenuItem.addActionListener(this::IngresarEdicionMenuItemActionPerformed);
        jMenu10.add(IngresarEdicionMenuItem);

        ConsultaEdicionMenuItem.setText("Consulta");
        ConsultaEdicionMenuItem.addActionListener(this::jMenuItem7ActionPerformed);
        jMenu10.add(ConsultaEdicionMenuItem);

        InscripcionEdicionMenuItem.setText("Inscripcion");
        InscripcionEdicionMenuItem.addActionListener(this::InscripcionEdicionMenuItemActionPerformed);
        jMenu10.add(InscripcionEdicionMenuItem);

        jMenu2.add(jMenu10);

        jMenuBar1.add(jMenu2);

        jMenu11.setText("Prog Formacion");

        CrearProgramaMenuItem.setText("Crear");
        CrearProgramaMenuItem.addActionListener(this::CrearProgramaMenuItemActionPerformed);
        jMenu11.add(CrearProgramaMenuItem);

        AgregarCursoProgramaMenuItem.setText("Agregar Curso");
        AgregarCursoProgramaMenuItem.addActionListener(this::AgregarCursoProgramaMenuItemActionPerformed);
        jMenu11.add(AgregarCursoProgramaMenuItem);

        ConsultaProgramaMenuItem.setText("Consultar");
        ConsultaProgramaMenuItem.addActionListener(this::ConsultaProgramaMenuItemActionPerformed);
        jMenu11.add(ConsultaProgramaMenuItem);

        InscripcionProgramaMenuItem.setText("Inscripcion");
        InscripcionProgramaMenuItem.addActionListener(this::InscripcionProgramaMenuItemActionPerformed);
        jMenu11.add(InscripcionProgramaMenuItem);

        jMenuBar1.add(jMenu11);

        jMenu12.setText("Instituto");

        AltaInstitutoMenuItem.setText("Alta Instituto");
        AltaInstitutoMenuItem.addActionListener(this::AltaInstitutoMenuItemActionPerformed);
        jMenu12.add(AltaInstitutoMenuItem);

        jMenuBar1.add(jMenu12);

        jMenu1.setText("Categoria");

        AltaCategoriaMenuItem.setText("Alta Categoria");
        AltaCategoriaMenuItem.addActionListener(this::AltaCategoriaMenuItemActionPerformed1);
        jMenu1.add(AltaCategoriaMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AltaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaUsuarioMenuItemActionPerformed
        // 1. Crear la instancia de la ventana interna
        AltaUsuario vAlta = new AltaUsuario();

        // 2. Asignas el tamaño exacto que tenga
        vAlta.setSize(432, 432); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vAlta);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAlta.getSize();
        vAlta.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vAlta.setVisible(true);
        vAlta.toFront();
    }//GEN-LAST:event_AltaUsuarioMenuItemActionPerformed


    private void CrearProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearProgramaMenuItemActionPerformed
                                              
    // 1. Crear una instancia de la ventana interna Programa_Formacion
    Crear_programa_formacion vCrearpf = new Crear_programa_formacion();
    vCrearpf.setSize(400,367);
    // 2. Agregarla al contenedor principal JDesktopPane
    jDesktopPane1.add(vCrearpf);
    
    // 3. Centrar la ventana dentro del escritorio
    java.awt.Dimension desktopSize = jDesktopPane1.getSize();
    java.awt.Dimension frameSize = vCrearpf.getSize();
    vCrearpf.setLocation((desktopSize.width - frameSize.width) / 2, 
                         (desktopSize.height - frameSize.height) / 2);
    
    // 4. Hacerla visible y traerla al frente
    vCrearpf.setVisible(true);
    vCrearpf.toFront();                                             

    }//GEN-LAST:event_CrearProgramaMenuItemActionPerformed

    private void IngresarCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarCursoMenuItemActionPerformed
        // 1. Crear la instancia de la ventana interna
        AltaCurso vAlta = new AltaCurso();

        // 2. Asignas el tamaño exacto que tenga
        vAlta.setSize(435, 602); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vAlta);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAlta.getSize();
        vAlta.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vAlta.setVisible(true);
        vAlta.toFront();
    }//GEN-LAST:event_IngresarCursoMenuItemActionPerformed

    private void ConsultaCursoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaCursoMenuItemActionPerformed
        ConsultaCurso vConsultaCurso = new ConsultaCurso();
        vConsultaCurso.setSize(355,469);
        // 2. Agregarla al contenedor principal JDesktopPane
        // (Asegúrate de que 'jDesktopPane1' sea el nombre de variable de tu JDesktopPane)
        jDesktopPane1.add(vConsultaCurso);
    
        // 3. Centrar la ventana dentro del escritorio
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vConsultaCurso.getSize();
        vConsultaCurso.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
    
        // 4. Hacerla visible y traerla al frente
        
        vConsultaCurso.setVisible(true);
        vConsultaCurso.toFront();
    }//GEN-LAST:event_ConsultaCursoMenuItemActionPerformed


    private void IngresarEdicionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarEdicionMenuItemActionPerformed
        AltaEdicionCurso vAltaEdicionCurso = new AltaEdicionCurso();
        vAltaEdicionCurso.setSize(355,469);
        // 2. Agregarla al contenedor principal JDesktopPane
        // (Asegúrate de que 'jDesktopPane1' sea el nombre de variable de tu JDesktopPane)
        jDesktopPane1.add(vAltaEdicionCurso);
    
        // 3. Centrar la ventana dentro del escritorio
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAltaEdicionCurso.getSize();
        vAltaEdicionCurso.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
    
        // 4. Hacerla visible y traerla al frente
        
        vAltaEdicionCurso.setVisible(true);
        vAltaEdicionCurso.toFront();
    }//GEN-LAST:event_IngresarEdicionMenuItemActionPerformed

    private void ConsultaUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaUsuarioMenuItemActionPerformed
       ConsultaUsuario vConsultaUsuario = new ConsultaUsuario();
       vConsultaUsuario.setSize(582,383);
        jDesktopPane1.add(vConsultaUsuario);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vConsultaUsuario.getSize();
        vConsultaUsuario.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vConsultaUsuario.setVisible(true);
        vConsultaUsuario.toFront();
    }//GEN-LAST:event_ConsultaUsuarioMenuItemActionPerformed

    private void AltaInstitutoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaInstitutoMenuItemActionPerformed
      AltaInstituto vAltaInstituto = new AltaInstituto();
      vAltaInstituto.setSize(385,172);
       jDesktopPane1.add(vAltaInstituto);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAltaInstituto.getSize();
        vAltaInstituto.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vAltaInstituto.setVisible(true);
        vAltaInstituto.toFront();
      
    }//GEN-LAST:event_AltaInstitutoMenuItemActionPerformed

    private void AgregarCursoProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCursoProgramaMenuItemActionPerformed
      
        AgregarCursoProgramaForm vAgCurProgForm = new AgregarCursoProgramaForm();
        vAgCurProgForm.setSize(344,503);
        jDesktopPane1.add(vAgCurProgForm);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAgCurProgForm.getSize();
        vAgCurProgForm.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vAgCurProgForm.setVisible(true);
        vAgCurProgForm.toFront();
    }//GEN-LAST:event_AgregarCursoProgramaMenuItemActionPerformed

    private void ConsultaProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaProgramaMenuItemActionPerformed
        ConsultaProgramaFormacion vConProgForm = new interfaces.ConsultaProgramaFormacion();
        vConProgForm.setSize(357,310);
        jDesktopPane1.add(vConProgForm);
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vConProgForm.getSize();
        vConProgForm.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vConProgForm.setVisible(true);
        vConProgForm.toFront();
    }//GEN-LAST:event_ConsultaProgramaMenuItemActionPerformed


    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ConsultaEdicionCurso vConsultaEdicion = new ConsultaEdicionCurso();
        vConsultaEdicion.setSize(406,368);
        jDesktopPane1.add(vConsultaEdicion);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vConsultaEdicion.getSize();
        vConsultaEdicion.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vConsultaEdicion.setVisible(true);
        vConsultaEdicion.toFront();
    }//GEN-LAST:event_jMenuItem7ActionPerformed


    private void InscripcionEdicionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionEdicionMenuItemActionPerformed
        InscripcionEdicionCurso vInscripcionEdicion = new InscripcionEdicionCurso();
        vInscripcionEdicion.setSize(400,500);
        jDesktopPane1.add(vInscripcionEdicion);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vInscripcionEdicion.getSize();
        vInscripcionEdicion.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vInscripcionEdicion.setVisible(true);
        vInscripcionEdicion.toFront();
    }//GEN-LAST:event_InscripcionEdicionMenuItemActionPerformed

    private void InscripcionProgramaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InscripcionProgramaMenuItemActionPerformed
        InscripcionProgramaDeFormacion vInscripcionPrograma = new InscripcionProgramaDeFormacion();
        vInscripcionPrograma.setSize(412,500);
        jDesktopPane1.add(vInscripcionPrograma);
         java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vInscripcionPrograma.getSize();
        vInscripcionPrograma.setLocation((desktopSize.width - frameSize.width) / 2, 
                      (desktopSize.height - frameSize.height) / 2);
        vInscripcionPrograma.setVisible(true);
        vInscripcionPrograma.toFront();
    }//GEN-LAST:event_InscripcionProgramaMenuItemActionPerformed

    private void AltaCategoriaMenuItemActionPerformed1(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AltaCategoriaMenuItemActionPerformed1
        // 1. Crear la instancia de la ventana interna
        AltaCategoria vAlta = new AltaCategoria();

        // 2. Asignas el tamaño exacto que tenga
        vAlta.setSize(334, 171); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vAlta);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vAlta.getSize();
        vAlta.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vAlta.setVisible(true);
        vAlta.toFront();
    }//GEN-LAST:event_AltaCategoriaMenuItemActionPerformed1

    private void ModificarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioMenuItemActionPerformed
        // 1. Crear la instancia de la ventana interna
        ModificarDatosdeUsuario vMod = new ModificarDatosdeUsuario();

        // 2. Asignas el tamaño exacto que tenga
        vMod.setSize(490, 602); 

        // 3. Agregarla al desktop panel principal
        jDesktopPane1.add(vMod);

        // 4. Centrar la ventana
        java.awt.Dimension desktopSize = jDesktopPane1.getSize();
        java.awt.Dimension frameSize = vMod.getSize();
        vMod.setLocation((desktopSize.width - frameSize.width) / 2, 
                          (desktopSize.height - frameSize.height) / 2);

        // 5. Hacerla visible y traerla al frente
        vMod.setVisible(true);
        vMod.toFront();
    }//GEN-LAST:event_ModificarUsuarioMenuItemActionPerformed
                                        



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Presentacion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AgregarCursoProgramaMenuItem;
    private javax.swing.JMenuItem AltaCategoriaMenuItem;
    private javax.swing.JMenuItem AltaInstitutoMenuItem;
    private javax.swing.JMenuItem AltaUsuarioMenuItem;
    private javax.swing.JMenuItem ConsultaCursoMenuItem;
    private javax.swing.JMenuItem ConsultaEdicionMenuItem;
    private javax.swing.JMenuItem ConsultaProgramaMenuItem;
    private javax.swing.JMenuItem ConsultaUsuarioMenuItem;
    private javax.swing.JMenuItem CrearProgramaMenuItem;
    private javax.swing.JMenuItem IngresarCursoMenuItem;
    private javax.swing.JMenuItem IngresarEdicionMenuItem;
    private javax.swing.JMenuItem InscripcionEdicionMenuItem;
    private javax.swing.JMenuItem InscripcionProgramaMenuItem;
    private javax.swing.JMenu ModUsuario;
    private javax.swing.JMenuItem ModificarUsuarioMenuItem;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    // End of variables declaration//GEN-END:variables
}
