/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;

import Logica.IController;
import java.awt.HeadlessException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author manuelpalumbo
 */
public class AgregarCursoProgramaForm extends javax.swing.JInternalFrame {
private IController icon;
    
    public AgregarCursoProgramaForm() {
        initComponents();
        initComponents();
        this.icon = icon;
        
        // Cargar las listas en los combos al abrir la ventana
        cargarProgramas();
        cargarCursos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbProgForm = new javax.swing.JComboBox<>();
        cbCurso = new javax.swing.JComboBox<>();
        btAceptar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setTitle("Agregar Curso");

        cbProgForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProgForm.addActionListener(this::cbProgFormActionPerformed);

        cbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(this::btAceptarActionPerformed);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(this::btCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btAceptar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cbCurso, 0, 190, Short.MAX_VALUE)
                    .addComponent(cbProgForm, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(cbProgForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAceptar)
                    .addComponent(btCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
  this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void cbProgFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProgFormActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProgFormActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
   String nomPrograma = (String) cbProgForm.getSelectedItem();
        String nomCurso = (String) cbCurso.getSelectedItem();

        // Validaciones de selección
        if (nomPrograma == null || nomPrograma.equals("Seleccione un Programa")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un programa de formación.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (nomCurso == null || nomCurso.equals("Seleccione un Curso")) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un curso.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Invocar el método del controlador
            icon.AgregarCursoAProgramas(nomPrograma, nomCurso);
            JOptionPane.showMessageDialog(this, "Curso agregado al programa con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            this.dispose(); // Cierra el JInternalFrame al terminar
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, "Error al agregar el curso: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAceptar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbProgForm;
    // End of variables declaration//GEN-END:variables

    private void cargarProgramas() {
DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Seleccione un Programa");
        cbProgForm.setModel(model);    }

    private void cargarCursos() {
DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        model.addElement("Seleccione un Curso"); 
        cbCurso.setModel(model);
     }
}
