/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;
import java.util.List;
import java.util.ArrayList;
import Logica.Fabric;
import Logica.IController;
import java.util.Date;
/**
 *
 * @author mateo
 */
public class AltaEdicionCurso extends javax.swing.JInternalFrame {
    IController ico;
    /**
     * Creates new form AltaEdicionCurso
     */
    public AltaEdicionCurso() {
        Fabric f = Fabric.GetInstance();
        ico = f.GetIController();
        initComponents();
        spinnerCupo.setVisible(false);
        labelNombreRepetido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        spinDateIni = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        spinDateFin = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        checkCupo = new javax.swing.JCheckBox();
        spinnerCupo = new javax.swing.JSpinner();
        boxDocentes = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        spinDateAlta = new javax.swing.JSpinner();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        boxInstituto = new javax.swing.JComboBox<>();
        boxCursos = new javax.swing.JComboBox<>();
        labelNombreRepetido = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta Edicion Curso");
        setToolTipText("");
        setPreferredSize(new java.awt.Dimension(366, 400));
        getContentPane().setLayout(null);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Cursos*");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(17, 56, 58, 26);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Instituto*");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(17, 18, 58, 26);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Nombre*");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(17, 100, 70, 26);

        fieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldNombreFocusLost(evt);
            }
        });
        getContentPane().add(fieldNombre);
        fieldNombre.setBounds(80, 100, 213, 26);

        spinDateIni.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        spinDateIni.setEditor(new javax.swing.JSpinner.DateEditor(spinDateIni, "dd/MM/yyyy"));
        getContentPane().add(spinDateIni);
        spinDateIni.setBounds(63, 166, 97, 26);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Inicio*");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(17, 165, 50, 26);

        spinDateFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        spinDateFin.setEditor(new javax.swing.JSpinner.DateEditor(spinDateFin, "dd/MM/yyyy"));
        getContentPane().add(spinDateFin);
        spinDateFin.setBounds(197, 168, 97, 22);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Fin*");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(166, 168, 40, 20);

        checkCupo.setText("Cupo Definido");
        checkCupo.addChangeListener(this::checkCupoStateChanged);
        getContentPane().add(checkCupo);
        checkCupo.setBounds(17, 211, 120, 20);
        getContentPane().add(spinnerCupo);
        spinnerCupo.setBounds(136, 210, 64, 22);

        boxDocentes.insertItemAt("Seleccionar...", 0);
        List<String> auxListDoc = ico.ListarDocentes();

        for(int i = 0;i<auxListDoc.size();i++){
            boxDocentes.insertItemAt(auxListDoc.get(i), i+1);
        }
        boxDocentes.setSelectedIndex(0);
        boxDocentes.addActionListener(this::boxDocentesActionPerformed);
        getContentPane().add(boxDocentes);
        boxDocentes.setBounds(87, 246, 250, 22);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Docente*");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(17, 238, 64, 36);

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Fecha de publicacion*");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(17, 282, 150, 26);

        spinDateAlta.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        spinDateAlta.setEditor(new javax.swing.JSpinner.DateEditor(spinDateAlta, "dd/MM/yyyy"));
        getContentPane().add(spinDateAlta);
        spinDateAlta.setBounds(167, 280, 97, 32);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(250, 330, 90, 23);

        btnCancelar.setForeground(new java.awt.Color(255, 102, 102));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(150, 330, 90, 23);

        boxInstituto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boxInstituto.insertItemAt("SIN DATOS", 0);
        List<String> auxListIns = ico.ListarInstitutos();

        for(int i = 0;i<auxListIns.size();i++){
            boxInstituto.insertItemAt(auxListIns.get(i), i+1);
        }
        boxInstituto.setSelectedIndex(0);
        boxInstituto.addActionListener(this::boxInstitutoActionPerformed);
        getContentPane().add(boxInstituto);
        boxInstituto.setBounds(82, 18, 212, 26);

        boxCursos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        boxCursos.addActionListener(this::boxCursosActionPerformed);
        getContentPane().add(boxCursos);
        boxCursos.setBounds(81, 56, 212, 26);

        labelNombreRepetido.setForeground(new java.awt.Color(255, 0, 0));
        labelNombreRepetido.setText("Nombre de edicion ya existente");
        getContentPane().add(labelNombreRepetido);
        labelNombreRepetido.setBounds(90, 130, 180, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDocentesActionPerformed
        String auxString = boxDocentes.getSelectedItem().toString();
        if(boxDocentes.getSelectedIndex()!=0){
            if(auxString.contains("✓")){
                String auxSubString = auxString.substring(2);
                int auxInt = boxDocentes.getSelectedIndex();
                boxDocentes.removeItemAt(auxInt);
                boxDocentes.insertItemAt(auxSubString, auxInt);
            }else{
                auxString = "✓ " + auxString;
                int auxInt = boxDocentes.getSelectedIndex();
                boxDocentes.removeItemAt(auxInt);
                boxDocentes.insertItemAt(auxString, auxInt);
                boxDocentes.setSelectedIndex(auxInt);
            }
        }
        
    }//GEN-LAST:event_boxDocentesActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        //Llamar a crear edicion de curso
        if(VerificarDatos()){
            javax.swing.JOptionPane.showMessageDialog(this, "Algunos campos deben ser completados", "Atencion",javax.swing.JOptionPane.ERROR_MESSAGE);
        }else{
            //Logica agregar edicion de curso
            String auxCurso = (String)boxCursos.getSelectedItem();
            String auxNombre = fieldNombre.getText();
            Date auxFIni = (Date)spinDateIni.getValue();
            Date auxFEnd = (Date)spinDateFin.getValue();
            
            List<String> docentes = new ArrayList();
            int tam = boxDocentes.getItemCount();
            for(int i = 1;i<tam;i++){
                String text = (String) boxDocentes.getItemAt(i);
                if(text.contains("✓")){
                    String auxSubString = text.substring(2);
                    docentes.add(auxSubString);
                }
            }
            Date auxFAlta = (Date)spinDateAlta.getValue();
            if(checkCupo.isSelected()==true){
                int auxCupo = (int)spinnerCupo.getValue();
                ico.AltaEdicionCurso(auxCurso, auxNombre, auxFIni, auxFEnd, auxCupo, docentes, auxFAlta);
            }else{
                ico.AltaEdicionCurso(auxCurso, auxNombre, auxFIni, auxFEnd, 0, docentes, auxFAlta);
            }
            javax.swing.JOptionPane.showMessageDialog(this, "Edicion de Curso ingresada con exito!", "System",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        
        }
    }//GEN-LAST:event_btnAceptarActionPerformed
    boolean VerificarDatos(){
        return boxInstituto.getSelectedIndex()==0 ||
                boxCursos.getSelectedIndex()==0 ||
                fieldNombre.getText().isEmpty() ||
                ico.VerificarEdicionCurso(fieldNombre.getText()) || 
                boxDocentes.getSelectedIndex()==0;
                
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Simplemente cierra la ventana interna sin cerrar el programa
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void checkCupoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkCupoStateChanged
        spinnerCupo.setVisible(checkCupo.isSelected());
    }//GEN-LAST:event_checkCupoStateChanged

    private void boxInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxInstitutoActionPerformed
        if(boxInstituto.getSelectedIndex()!=0){
            List<String> auxListCur = ico.ListarCursos((String) boxInstituto.getSelectedItem());
            boxCursos.insertItemAt("SIN DATOS", 0);
            for(int i = 0;i<auxListCur.size();i++){
                boxCursos.insertItemAt(auxListCur.get(i), i+1);
            }
            boxCursos.setSelectedIndex(0);
        }

    }//GEN-LAST:event_boxInstitutoActionPerformed

    private void boxCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxCursosActionPerformed
        

    }//GEN-LAST:event_boxCursosActionPerformed

    private void fieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldNombreFocusLost
        if(ico.VerificarEdicionCurso(fieldNombre.getText())){
            labelNombreRepetido.setVisible(true);
        }else{
            labelNombreRepetido.setVisible(false);
        }
    }//GEN-LAST:event_fieldNombreFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxCursos;
    private javax.swing.JComboBox<String> boxDocentes;
    private javax.swing.JComboBox<String> boxInstituto;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JCheckBox checkCupo;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel labelNombreRepetido;
    private javax.swing.JSpinner spinDateAlta;
    private javax.swing.JSpinner spinDateFin;
    private javax.swing.JSpinner spinDateIni;
    private javax.swing.JSpinner spinnerCupo;
    // End of variables declaration//GEN-END:variables
}
