/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;

import Logica.IController;
import Logica.Fabric;


import java.io.File;
import javax.swing.JFileChooser;
import java.util.Date;
import java.util.Calendar;

import java.util.List;
import java.util.ArrayList;

import java.io.File;
import javax.swing.ImageIcon;
/**
 *
 * @author sebas
 */
public class AltaUsuario extends javax.swing.JInternalFrame {
    public IController ico;
    /**
     * Creates new form AltaUsuario
     */
    public AltaUsuario() {
        Fabric f = Fabric.GetInstance();
        ico = f.GetIController();
        initComponents();
        
        // Ocultar la etiqueta y el combo box de Instituto al cargar la ventana
       lblInstituto.setVisible(false);
       comboInstituto.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNickname = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        comboTipoUsuario = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        comboInstituto = new javax.swing.JComboBox<>();
        lblInstituto = new javax.swing.JLabel();
        fieldPath = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buttonChooser = new javax.swing.JButton();
        spinnerDate = new javax.swing.JSpinner();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Alta de Usuario");
        getContentPane().setLayout(null);

        jLabel1.setText("Nickname:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 53, 70, 16);

        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 84, 70, 16);

        jLabel3.setText("Apellido:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 109, 70, 16);

        jLabel4.setText("Email:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(36, 137, 60, 16);

        txtNickname.addActionListener(this::txtNicknameActionPerformed);
        getContentPane().add(txtNickname);
        txtNickname.setBounds(183, 53, 154, 22);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(183, 81, 154, 22);

        txtApellido.addActionListener(this::txtApellidoActionPerformed);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(183, 109, 154, 22);

        txtEmail.addActionListener(this::txtEmailActionPerformed);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(183, 137, 154, 22);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);
        getContentPane().add(btnAceptar);
        btnAceptar.setBounds(250, 350, 90, 23);

        btnCancelar.setForeground(new java.awt.Color(255, 102, 102));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(150, 350, 90, 23);

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("Ingrese datos de usuario:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(19, 17, 160, 18);

        jLabel6.setText("Tipo de usuario:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 210, 100, 20);

        comboTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Estudiante", "Docente" }));
        comboTipoUsuario.addActionListener(this::comboTipoUsuarioActionPerformed);
        getContentPane().add(comboTipoUsuario);
        comboTipoUsuario.setBounds(180, 210, 151, 22);

        jLabel10.setText("Fecha de Nacimiento:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 180, 130, 20);

        List<String> auxListIns = ico.ListarInstitutos();
        comboInstituto.insertItemAt("Seleccionar...", 0);
        for(int i = 0;i<auxListIns.size();i++){
            comboInstituto.insertItemAt(auxListIns.get(i), i+1);
        }
        comboInstituto.setSelectedIndex(0);
        comboInstituto.addActionListener(this::comboInstitutoActionPerformed);
        getContentPane().add(comboInstituto);
        comboInstituto.setBounds(180, 240, 151, 22);

        lblInstituto.setText("Instituto");
        getContentPane().add(lblInstituto);
        lblInstituto.setBounds(30, 240, 100, 20);
        getContentPane().add(fieldPath);
        fieldPath.setBounds(140, 270, 161, 22);

        jLabel11.setText("Imagen");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 270, 100, 20);

        buttonChooser.setText("...");
        buttonChooser.addActionListener(this::buttonChooserActionPerformed);
        getContentPane().add(buttonChooser);
        buttonChooser.setBounds(310, 270, 23, 23);

        spinnerDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        spinnerDate.setEditor(new javax.swing.JSpinner.DateEditor(spinnerDate, "dd/MM/yyyy"));
        getContentPane().add(spinnerDate);
        spinnerDate.setBounds(183, 177, 144, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNicknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicknameActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
          // 1. Captura de datos básicos de texto
    String nickname = txtNickname.getText().trim();
    String nombre = txtNombre.getText().trim();
    String apellido = txtApellido.getText().trim();
    String email = txtEmail.getText().trim();

    // 2. Captura de la Fecha de los Spinners
    Date fecha =(Date) spinnerDate.getValue();
    Calendar cal = Calendar.getInstance();
    cal.setTime(fecha);
    int dia = cal.get(Calendar.DAY_OF_MONTH);
    int mes = cal.get(Calendar.MONTH)+1;
    int anio = cal.get(Calendar.YEAR);

    // 3. Validación de campos obligatorios de texto
    if (nickname.isEmpty() || email.isEmpty() || nombre.isEmpty() || apellido.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Por favor, complete todos los campos de texto obligatorios.", 
            "Campos Incompletos", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 4. Validación del Combo Tipo de Usuario (posición 0 es "Seleccionar...")
    if (comboTipoUsuario.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Debe seleccionar un Tipo de Usuario válido.", 
            "Atención", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String tipoUsuario = (String) comboTipoUsuario.getSelectedItem();

    // 5. Validación del Instituto (SI Y SOLO SI es Docente)
    if ("Docente".equalsIgnoreCase(tipoUsuario)) {
        if (comboInstituto.getSelectedIndex() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Debe seleccionar un Instituto para el Docente.", 
                "Atención", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
    }

    // 6. Proceso de Alta (Paso exitoso)
    try {
        // Armar la fecha
        Calendar cale = Calendar.getInstance();
        cal.set(anio, mes - 1, dia);
        Date fechaNacimiento = cale.getTime();

        String instituto = (String)comboInstituto.getSelectedItem();
        String ruta  = fieldPath.getText();
        ImageIcon icon = new ImageIcon(ruta);
        if ("Docente".equalsIgnoreCase(tipoUsuario)) {
            ico.AltaUsuario(nickname, nombre, apellido, nombre, fechaNacimiento, true, instituto, icon);
        } else {
            ico.AltaUsuario(nickname, nombre, apellido, nombre, fechaNacimiento, false, instituto, icon);
        }

        // Mensaje de éxito
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Usuario '" + nickname + "' registrado con éxito como " + tipoUsuario + ".", 
            "Alta Exitosa", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // Cerrar la ventana interna
        this.dispose();

    } catch (Exception ex) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error al registrar en el sistema: " + ex.getMessage(), 
            "Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }   
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Simplemente cierra la ventana interna sin cerrar el programa
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboTipoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoUsuarioActionPerformed
        String tipo = (String) comboTipoUsuario.getSelectedItem();
    
    // Si selecciona "Docente", hacemos VISIBLES los elementos
    if ("Docente".equalsIgnoreCase(tipo)) {
        lblInstituto.setVisible(true);
        comboInstituto.setVisible(true);
    } else {
        // Si selecciona "Estudiante" o "Seleccionar...", los OCULTAMOS y reiniciamos la selección
        lblInstituto.setVisible(false);
        comboInstituto.setVisible(false);
        comboInstituto.setSelectedIndex(0);
    }
    }//GEN-LAST:event_comboTipoUsuarioActionPerformed

    private void comboInstitutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInstitutoActionPerformed
        
    }//GEN-LAST:event_comboInstitutoActionPerformed

    private void buttonChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonChooserActionPerformed
        //Evento para elegir imagen
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes JPG y PNG", "jpg", "png"));
        int resultado = chooser.showOpenDialog(this);
        if(resultado == JFileChooser.APPROVE_OPTION){
            File archivo = chooser.getSelectedFile();
            fieldPath.setText(archivo.getAbsolutePath());
        }
    }//GEN-LAST:event_buttonChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton buttonChooser;
    private javax.swing.JComboBox<String> comboInstituto;
    private javax.swing.JComboBox<String> comboTipoUsuario;
    private javax.swing.JTextField fieldPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblInstituto;
    private javax.swing.JSpinner spinnerDate;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNickname;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
