/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;
import Logica.Fabric;
import Logica.IController;
/**
 *
 * @author manuelpalumbo
 */
public class Crear_programa_formacion extends javax.swing.JInternalFrame {
    IController ico;
    /**
     * Creates new form Crear_programa_formacion
     */
    public Crear_programa_formacion() {
        Fabric f = Fabric.GetInstance();
        ico = f.GetIController();
        
        initComponents();
        this.setClosable(true);    
        this.setIconifiable(true); 
        this.setMaximizable(true); 
        this.setResizable(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreProg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcionPorg = new javax.swing.JTextArea();
        fechaIni = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        Fechafin = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setTitle("Crear Programa de Formacion");

        jLabel1.setText("Nombre Programa");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Ingrese datos del Programa");

        txtNombreProg.addActionListener(this::txtNombreProgActionPerformed);

        jLabel3.setText("Descripcion");

        txtDescripcionPorg.setColumns(20);
        txtDescripcionPorg.setLineWrap(true);
        txtDescripcionPorg.setRows(5);
        txtDescripcionPorg.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtDescripcionPorg);

        fechaIni.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        fechaIni.setToolTipText("");
        fechaIni.setEditor(new javax.swing.JSpinner.DateEditor(fechaIni, "dd/MM/yyyy"));

        jLabel4.setText("Fecha de inicio");

        Fechafin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        Fechafin.setToolTipText("");
        Fechafin.setEditor(new javax.swing.JSpinner.DateEditor(Fechafin, "dd/MM/yyyy"));

        jLabel5.setText("Fecha de Finalizacion");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombreProg, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Fechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(55, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fechaIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fechafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProgActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreProg = txtNombreProg.getText().trim();
        String descripcionProg = txtDescripcionPorg.getText().trim();
        java.util.Date fechaInicio = (java.util.Date) fechaIni.getValue();
        java.util.Date fechaFin = (java.util.Date) Fechafin.getValue();
        
        if(nombreProg.isEmpty() || descripcionProg.isEmpty()){
         javax.swing.JOptionPane.showMessageDialog(
            this, 
            "Error: Todos los campos son obligatorios", 
            "Campos Inválidos", 
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }else{
            boolean existe = ico.ExistePrograma(nombreProg);
            if(existe){
            int respuesta = javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "El programa '" + nombreProg + "' ya existe. ¿Deseas modificar sus datos?", 
            "Programa Existente", 
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE
        );
            
            if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            // El usuario quiere modificarlo
            ico.ActualizarPrograma(nombreProg, descripcionProg, fechaInicio, fechaFin);
            javax.swing.JOptionPane.showMessageDialog(this, "Programa actualizado con éxito.");
            this.dispose();
          
            }else {
            // El usuario canceló la operación
            javax.swing.JOptionPane.showMessageDialog(this, "Operación cancelada.");
            this.dispose();
            }
        }else{
                javax.swing.JOptionPane.showMessageDialog(this, "¡Programa de formación creado con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
       this.dispose();
            }
        }
        

        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Fechafin;
    private javax.swing.JSpinner fechaIni;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtDescripcionPorg;
    private javax.swing.JTextField txtNombreProg;
    // End of variables declaration//GEN-END:variables
}
