/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;
import Logica.Fabric;
import Logica.IController;
import java.util.Date;
/**
 *
 * @author manuelpalumbo
 */
public class Crear_programa_formacion extends javax.swing.JInternalFrame {
    IController ico;
    /**
     * Creates new form Crear_programa_formacion
     */
    public Crear_programa_formacion() {
        Fabric f = Fabric.GetInstance();
        ico = f.GetIController();
        
        initComponents();
        this.setClosable(true);    
        this.setIconifiable(true); 
        this.setMaximizable(true); 
        this.setResizable(true);   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        spinFInicio = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        spinFFin = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        spinFAlta = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Crear Programa de Formacion");

        jLabel1.setText("Nombre Programa");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Ingrese datos del Programa");

        fieldNombre.addActionListener(this::fieldNombreActionPerformed);

        jLabel3.setText("Descripcion");

        areaDescripcion.setColumns(20);
        areaDescripcion.setLineWrap(true);
        areaDescripcion.setRows(5);
        areaDescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(areaDescripcion);

        spinFInicio.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        spinFInicio.setToolTipText("");
        spinFInicio.setEditor(new javax.swing.JSpinner.DateEditor(spinFInicio, "dd/MM/yyyy"));

        jLabel4.setText("Fecha de inicio");

        spinFFin.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_MONTH));
        spinFFin.setToolTipText("");
        spinFFin.setEditor(new javax.swing.JSpinner.DateEditor(spinFFin, "dd/MM/yyyy"));

        jLabel5.setText("Fecha de Finalizacion");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        spinFAlta.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        spinFAlta.setToolTipText("");
        spinFAlta.setEditor(new javax.swing.JSpinner.DateEditor(spinFAlta, "dd/MM/yyyy"));

        jLabel6.setText("Fecha de Alta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(spinFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(spinFAlta)
                                                .addComponent(spinFFin)))))
                                .addGap(87, 87, 87))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinFInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinFFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinFAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nombreProg = fieldNombre.getText().trim();
        String descripcionProg = areaDescripcion.getText().trim();
        Date fechaInicio = (Date) spinFInicio.getValue();
        Date fechaFin = (Date) spinFFin.getValue();
        Date fAlta  = (Date)spinFAlta.getValue();
        
        if(nombreProg.isEmpty() || descripcionProg.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Error: Todos los campos son obligatorios", 
                "Campos Inválidos", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }else if(VerificarDatos()){
            javax.swing.JOptionPane.showMessageDialog(
                this, 
                "Error: Datos incoherentes", 
                "Campos Inválidos", 
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }else{
            if(ico.VerificarPrograma(nombreProg)){
                int respuesta = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "El programa '" + nombreProg + "' ya existe. ¿Deseas modificar sus datos?", 
                "Programa Existente", 
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE
                );
            
                if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
                    // El usuario quiere modificarlo
                    ico.CrearProgramasDeFormacion(nombreProg, descripcionProg,fechaInicio, fechaFin, fAlta);
                    javax.swing.JOptionPane.showMessageDialog(this, "Programa actualizado con éxito.");
                    this.dispose();
                }else {
                    // El usuario canceló la operación
                    javax.swing.JOptionPane.showMessageDialog(this, "Operación cancelada.");
                    this.dispose();
                }
            }else{
                ico.CrearProgramasDeFormacion(nombreProg, descripcionProg, fechaInicio, fechaFin, fAlta);
                javax.swing.JOptionPane.showMessageDialog(this, "¡Programa de formación creado con éxito!", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
private boolean VerificarDatos(){
        Date fecha1 = (Date)spinFInicio.getValue();
        Date fecha2 = (Date)spinFFin.getValue();
        Date fechaAlta = (Date)spinFAlta.getValue();
        
        return fecha1.after(fecha2) ||
                fechaAlta.after(fecha1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spinFAlta;
    private javax.swing.JSpinner spinFFin;
    private javax.swing.JSpinner spinFInicio;
    // End of variables declaration//GEN-END:variables
}
