/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaces;

import javax.swing.JList;

/**
 *
 * @author mateo
 */
public class InfoExtraDocente extends javax.swing.JPanel {

    /**
     * Creates new form InfoExtraDocente
     */
    public InfoExtraDocente() {
        initComponents();
    }
    public JList getListCursos(){
        return this.listCursos;
    }
    public JList getListEdiciones(){
        return this.listEdiciones;
    }
    public JList getListProgramas(){
        return this.listProgramas;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listCursos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listEdiciones = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        listProgramas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        listCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listCursos.addListSelectionListener(this::listCursosValueChanged);
        jScrollPane1.setViewportView(listCursos);

        add(jScrollPane1);
        jScrollPane1.setBounds(6, 28, 155, 146);

        listEdiciones.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listEdiciones.addListSelectionListener(this::listEdicionesValueChanged);
        jScrollPane2.setViewportView(listEdiciones);

        add(jScrollPane2);
        jScrollPane2.setBounds(167, 28, 155, 146);

        listProgramas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listProgramas.addListSelectionListener(this::listProgramasValueChanged);
        jScrollPane3.setViewportView(listProgramas);

        add(jScrollPane3);
        jScrollPane3.setBounds(328, 28, 155, 146);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cursos");
        add(jLabel1);
        jLabel1.setBounds(6, 6, 155, 16);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Ediciones de Cursos");
        add(jLabel2);
        jLabel2.setBounds(167, 6, 155, 16);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Programas de Formacion");
        add(jLabel3);
        jLabel3.setBounds(328, 6, 155, 16);
    }// </editor-fold>//GEN-END:initComponents

    private void listCursosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listCursosValueChanged
        //ConsultaCurso
    }//GEN-LAST:event_listCursosValueChanged

    private void listEdicionesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEdicionesValueChanged
        //Consulta Ediciones
    }//GEN-LAST:event_listEdicionesValueChanged

    private void listProgramasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProgramasValueChanged
        //Consulta Programas de Formacion
    }//GEN-LAST:event_listProgramasValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> listCursos;
    private javax.swing.JList<String> listEdiciones;
    private javax.swing.JList<String> listProgramas;
    // End of variables declaration//GEN-END:variables
}
