/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;
import javax.swing.JOptionPane;
/**
 *
 * @author sebas
 */
public class InscripcionEdicionCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form InscripcionEdicionCurso
     */
    public InscripcionEdicionCurso() {
        initComponents();
        // Ocultar visibilidades iniciales
        lblCurso.setVisible(false);
        comboCursos.setVisible(false);
        lblEdicion.setVisible(false);
        comboEdiciones.setVisible(false);
        lblDetalle.setVisible(false);
        txtDetalleEdicion.setVisible(false);
    
    // Cargar los mock data
    cargarDatosPrueba();        
    }
    
    private void cargarDatosPrueba() {
        // 1. Cargar Combo de Estudiantes
    comboEstudiantes.removeAllItems();
    comboEstudiantes.addItem("Seleccione Estudiante...");
    comboEstudiantes.addItem("jperez - Juan Pérez");
    comboEstudiantes.addItem("mgomez - María Gómez");
    comboEstudiantes.addItem("lrodriguez - Lucas Rodríguez");

    // 2. Cargar Combo de Institutos
    comboInstitutos.removeAllItems();
    comboInstitutos.addItem("Seleccione Instituto...");
    comboInstitutos.addItem("INCO - Instituto de Computación");
    comboInstitutos.addItem("IMERL - Instituto de Matemática");

    // 3. Configurar el área de texto de detalle (Lectura solamente)
    txtDetalleEdicion.setEditable(false);
    txtDetalleEdicion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEstudiantes = new javax.swing.JComboBox<>();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        comboInstitutos = new javax.swing.JComboBox<>();
        comboCursos = new javax.swing.JComboBox<>();
        comboEdiciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDetalleEdicion = new javax.swing.JTextPane();
        lblEstudiante = new javax.swing.JLabel();
        lblInstituto = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();
        lblEdicion = new javax.swing.JLabel();
        lblDetalle = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscripción a Edición de Curso");

        comboEstudiantes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEstudiantes.addActionListener(this::comboEstudiantesActionPerformed);

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(this::btnAceptarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        comboInstitutos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboInstitutos.addActionListener(this::comboInstitutosActionPerformed);

        comboCursos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboCursos.addActionListener(this::comboCursosActionPerformed);

        comboEdiciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEdiciones.addActionListener(this::comboEdicionesActionPerformed);

        jScrollPane1.setViewportView(txtDetalleEdicion);

        lblEstudiante.setText("Estudiante:");

        lblInstituto.setText("Instituto:");

        lblCurso.setText("Curso:");

        lblEdicion.setText("Edición:");

        lblDetalle.setText("Información de la Edición:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblEstudiante)
                                .addComponent(lblEdicion, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblCurso, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(lblInstituto))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAceptar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(comboEstudiantes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboInstitutos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboCursos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboEdiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDetalle))
                        .addGap(0, 25, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblEstudiante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInstituto)
                        .addGap(12, 12, 12)
                        .addComponent(lblCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEdicion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(comboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboInstitutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboEdiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addComponent(lblDetalle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboInstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboInstitutosActionPerformed
        if (comboInstitutos.getSelectedIndex() > 0) {
        String inst = (String) comboInstitutos.getSelectedItem();
        
        comboCursos.removeAllItems();
        comboCursos.addItem("Seleccione Curso...");

        // Carga simulada según el instituto
        if (inst.contains("INCO")) {
            comboCursos.addItem("Programación de Aplicaciones");
            comboCursos.addItem("Estructura de Datos");
        } else if (inst.contains("IMERL")) {
            comboCursos.addItem("Cálculo I");
            comboCursos.addItem("Álgebra Lineal");
        }

        // Mostrar elementos
        lblCurso.setVisible(true);
        comboCursos.setVisible(true);
        comboCursos.setEnabled(true);
    } else {
        // Resetear cascada si vuelve a "Seleccione..."
        lblCurso.setVisible(false);
        comboCursos.setVisible(false);
        lblEdicion.setVisible(false);
        comboEdiciones.setVisible(false);
        lblDetalle.setVisible(false);
        txtDetalleEdicion.setVisible(false);
    }
    }//GEN-LAST:event_comboInstitutosActionPerformed

    private void comboCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCursosActionPerformed
        if (comboCursos.isVisible() && comboCursos.getSelectedIndex() > 0) {
        String curso = (String) comboCursos.getSelectedItem();
        
        comboEdiciones.removeAllItems();
        comboEdiciones.addItem("Seleccione Edición...");

        // Carga simulada según el curso
        if (curso.equals("Programación de Aplicaciones")) {
            comboEdiciones.addItem("PA - Edición 2026 S2");
            comboEdiciones.addItem("PA - Intensivo Invierno");
        } else {
            comboEdiciones.addItem("Edición Regular 2026");
        }

        // Mostrar elementos
        lblEdicion.setVisible(true);
        comboEdiciones.setVisible(true);
        comboEdiciones.setEnabled(true);
    } else {
        lblEdicion.setVisible(false);
        comboEdiciones.setVisible(false);
        lblDetalle.setVisible(false);
        txtDetalleEdicion.setVisible(false);
    }
    }//GEN-LAST:event_comboCursosActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
       // 1. Validar elecciones en los combos
    if (comboEstudiantes.getSelectedIndex() <= 0) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un estudiante.", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (comboInstitutos.getSelectedIndex() <= 0 || comboCursos.getSelectedIndex() <= 0 || comboEdiciones.getSelectedIndex() <= 0) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un instituto, un curso y una edición.", "Atención", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Capturar seleccionados
    String estudiante = (String) comboEstudiantes.getSelectedItem();
    String edicion = (String) comboEdiciones.getSelectedItem();
    java.util.Date fechaActual = new java.util.Date(); // Fecha del momento de la inscripción

    // 3. Invocar caso de uso y manejar excepciones (ej. estudiante ya inscrito)
    try {
        /*
           controladorInscripcion.inscribirEstudiante(estudiante, edicion, fechaActual);
        */
        
        JOptionPane.showMessageDialog(this, "Inscripción realizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Error al inscribir: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // Cierra y destruye la ventana interna actual
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void comboEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstudiantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboEstudiantesActionPerformed

    private void comboEdicionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEdicionesActionPerformed
        if (comboEdiciones.isVisible() && comboEdiciones.getSelectedIndex() > 0) {
        String edicion = (String) comboEdiciones.getSelectedItem();
        
        // Simulación de los datos de la edición
        txtDetalleEdicion.setText(
            "INFORMACIÓN DE LA EDICIÓN\n" +
            "-----------------------------------\n" +
            "Nombre: " + edicion + "\n" +
            "Fecha Inicio: 01/09/2026\n" +
            "Fecha Fin: 15/12/2026\n" +
            "Cupos Máximos: 30\n" +
            "Cupos Disponibles: 12"
        );

        // Mostrar el panel de detalle
        lblDetalle.setVisible(true);
        txtDetalleEdicion.setVisible(true);
    } else {
        lblDetalle.setVisible(false);
        txtDetalleEdicion.setVisible(false);
    }
    }//GEN-LAST:event_comboEdicionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> comboCursos;
    private javax.swing.JComboBox<String> comboEdiciones;
    private javax.swing.JComboBox<String> comboEstudiantes;
    private javax.swing.JComboBox<String> comboInstitutos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JLabel lblDetalle;
    private javax.swing.JLabel lblEdicion;
    private javax.swing.JLabel lblEstudiante;
    private javax.swing.JLabel lblInstituto;
    private javax.swing.JTextPane txtDetalleEdicion;
    // End of variables declaration//GEN-END:variables
}
