/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package interfaces;

import DTsClasses.DTCurso;
import DTsClasses.DTMaster;
import java.awt.Desktop;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import java.net.URI;
import java.net.URISyntaxException;

import Logica.Fabric;
import Logica.IController;
import java.util.ArrayList;
/**
 *
 * @author mateo
 */
public class MiniInterfazDeConsultaCurso extends javax.swing.JInternalFrame {
    IController ico;
    DefaultListModel<String> modeloListEdiCurso;
    DefaultListModel<String> modeloListProgCurso;
    String URL;
    DTCurso dtc = null;
    
    public MiniInterfazDeConsultaCurso() {
        Fabric f = Fabric.GetInstance();
        ico = f.GetIController();
        initComponents();
        
    }
    public void ColocarDatos(DTMaster dtCurso){dtc = (DTCurso)dtCurso;
        dtc = (DTCurso)dtCurso;
        areaDescripcion.setText(dtc.getDescripcion());
        textDuracion.setText(String.valueOf(dtc.getDuracion()));
        textCantHoras.setText(String.valueOf(dtc.getCantHoras()));
        textCantCreditos.setText(String.valueOf(dtc.getCantCreditos()));
        URL = dtc.getURL();
        String linkText = "<html><a href=''>"+URL + "</a></html>";
        textURL.setText(linkText);
        LLenarTablasYListas();
        
        
        
        
        
        
        
    }
    private void LLenarTablasYListas(){
        if(dtc!=null){
            List<String>listEdi = dtc.getEdiCursos();
            if(listEdi!=null){
                int tamEdiCurso = listEdi.size();
                for(int i =0;i<tamEdiCurso;i++){
                    modeloListEdiCurso.addElement(dtc.getEdiCursos().get(i));
                }
            }
            List<String>listPro = dtc.getProgFormacion();
            if(listPro!=null){
                int tamProgCurso = dtc.getProgFormacion().size();
                for(int i =0;i<tamProgCurso;i++){
                    modeloListProgCurso.addElement(dtc.getProgFormacion().get(i));
                }
            }

            List<String> listStr = dtc.getPrevias();
            if(listStr!=null){
                int tamListPrevias = listStr.size();
                DefaultTableModel modelo = (DefaultTableModel) tablePrevias.getModel();
                for(int i=0;i<tamListPrevias;i++){
                    String str = listStr.get(i);
                    Object[] obj = {str};
                    modelo.addRow(obj);
                }
            }
        }else{
            System.out.println("Esto esta null");
        }
        
        
    }
            
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaDescripcion = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        textDuracion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        textCantHoras = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textCantCreditos = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listEdiCursos = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listProgFormacion = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        textURL = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tablePrevias = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Previas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
        }

        setClosable(true);
        setTitle("(Info) \"Nombre_Curso\"");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Descripcion");

        areaDescripcion.setEditable(false);
        areaDescripcion.setBackground(new java.awt.Color(255, 255, 255));
        areaDescripcion.setColumns(20);
        areaDescripcion.setRows(5);
        areaDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        areaDescripcion.setFocusable(false);
        jScrollPane1.setViewportView(areaDescripcion);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Duracion:");

        textDuracion.setEditable(false);
        textDuracion.setBackground(new java.awt.Color(255, 255, 255));
        textDuracion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textDuracion.setFocusable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Cant. Horas:");

        textCantHoras.setEditable(false);
        textCantHoras.setBackground(new java.awt.Color(255, 255, 255));
        textCantHoras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textCantHoras.setFocusable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Cant. Creditos:");

        textCantCreditos.setEditable(false);
        textCantCreditos.setBackground(new java.awt.Color(255, 255, 255));
        textCantCreditos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textCantCreditos.setFocusable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("URL:");

        modeloListEdiCurso = new DefaultListModel<>();
        listEdiCursos.setModel(modeloListEdiCurso);
        listEdiCursos.addListSelectionListener(this::listEdiCursosValueChanged);
        jScrollPane3.setViewportView(listEdiCursos);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ediciones de curso");

        modeloListProgCurso = new DefaultListModel<>();
        listProgFormacion.setModel(modeloListProgCurso);
        listProgFormacion.addListSelectionListener(this::listProgFormacionValueChanged);
        jScrollPane4.setViewportView(listProgFormacion);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Programas de Formacion");

        textURL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textURL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textURLMouseClicked(evt);
            }
        });

        tablePrevias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cursos Previos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePrevias.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int fila = tablePrevias.getSelectedRow();
                if (fila != -1) {
                    //Logica de mostrar curso
                    String nombre = (String)tablePrevias.getValueAt(fila, 0);
                    DTMaster dt = ico.ConsultaCurso(nombre);
                    MiniInterfazDeConsultaCurso micc = new MiniInterfazDeConsultaCurso();
                    this.getDesktopPane().add(micc);
                    micc.setTitle("(Info) "+nombre);
                    micc.setLocation(0, 0);

                    micc.setVisible(true);

                    try {
                        micc.setSelected(true);
                    } catch (java.beans.PropertyVetoException ex) {
                        ex.printStackTrace();
                    }

                    micc.toFront();
                    micc.ColocarDatos(dt);
                }
            }
        });
        jScrollPane7.setViewportView(tablePrevias);
        if (tablePrevias.getColumnModel().getColumnCount() > 0) {
            tablePrevias.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textURL, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textCantCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(textCantHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCantHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textCantCreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(textURL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listEdiCursosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listEdiCursosValueChanged
        //Logica ventana de consulta de edicion de curso
        //Este mensaje es de prueba para mostrar como se pide el valor que se toco
        javax.swing.JOptionPane.showMessageDialog(this, listEdiCursos.getSelectedValue(), "System",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_listEdiCursosValueChanged

    private void listProgFormacionValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listProgFormacionValueChanged
        //Logica ventana de consulta de edicion de curso
        //Este mensaje es de prueba para mostrar como se pide el valor que se toco
        javax.swing.JOptionPane.showMessageDialog(this, listProgFormacion.getSelectedValue(), "System",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_listProgFormacionValueChanged

    private void textURLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textURLMouseClicked

            try {
                try {
                    Desktop.getDesktop().browse(new URI(URL));
                } catch (IOException ex) {
                    System.getLogger(MiniInterfazDeConsultaCurso.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                }
            } catch (URISyntaxException ex) {
                System.getLogger(MiniInterfazDeConsultaCurso.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        
    }//GEN-LAST:event_textURLMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaDescripcion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JList<String> listEdiCursos;
    private javax.swing.JList<String> listProgFormacion;
    private javax.swing.JTable tablePrevias;
    private javax.swing.JTextField textCantCreditos;
    private javax.swing.JTextField textCantHoras;
    private javax.swing.JTextField textDuracion;
    private javax.swing.JLabel textURL;
    // End of variables declaration//GEN-END:variables
}
